version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TEST
    env_file:
      - .env
    # ports:
    #   - "8111:8000"
    restart: always
